name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Change branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest  # Adjust OS if preferred

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Update with your desired Python version

      - name: Check Network Connectivity (Optional)
        # Add this step if you suspect network issues
        run: ping 8.8.8.8 || true  # Silences non-zero exit code

      - name: Install dependencies (linter)
        # Specify PyPI URL (optional)
        run: pip install --index-url https://pypi.org stylelint

      - name: Configure Stylelint (Optional)
        # Add this step if you have a custom stylelint configuration file
        run: cp .stylelintrc ./  # Replace with your copy command

      - name: Run style checks
        run: stylelint --fix

     
